services:
  api:
    image: python:3.12-slim
    container_name: s2i-api
    working_dir: /app
    env_file:
      - .env.docker
    volumes:
      - ./:/app
    command: >
      sh -c "python -m pip install --upgrade pip &&
             uvicorn backend.app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    image: python:3.12-slim
    container_name: s2i-worker
    working_dir: /app
    env_file:
      - .env.docker
    volumes:
      - ./:/app
    command: >
      sh -c "python -m pip install --upgrade pip &&
             python -c 'print(\"worker placeholder up\")'"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
